"""Aggregate every registered contribution into a community report.

Pools card metadata (device, consent, license, frame counts) and, for in-repo
signal bundles, the actual signals (contact ratio, action magnitude) into one
summary + a human-readable REPORT.md. Hosted entries contribute their metadata
only (we never fetch remote data here).
"""

from __future__ import annotations

import json
import os
from collections import Counter
from typing import Dict, List, Optional

import numpy as np


def _load_signal_stats(registry_dir: str, data_path: str) -> Optional[Dict]:
    p = os.path.join(registry_dir, data_path, "signals.jsonl")
    if not os.path.exists(p):
        return None
    contacts, act_mag, n = [], [], 0
    with open(p) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            n += 1
            contacts.append(1.0 if r.get("contact") else 0.0)
            a = r.get("action", [0.0, 0.0])
            act_mag.append(float((a[0] ** 2 + a[1] ** 2) ** 0.5))
    return {
        "n": n,
        "contact_ratio": float(np.mean(contacts)) if contacts else 0.0,
        "mean_action_magnitude": float(np.mean(act_mag)) if act_mag else 0.0,
    }


def _load_cards(registry_dir: str) -> List[Dict]:
    index = os.path.join(registry_dir, "datasets.jsonl")
    cards: List[Dict] = []
    if os.path.exists(index):
        with open(index) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                try:
                    cards.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    return cards


def aggregate_registry(registry_dir: str = "registry") -> Dict:
    cards = _load_cards(registry_dir)
    devices, consents, licenses, modes = Counter(), Counter(), Counter(), Counter()
    total_frames = total_eps = 0
    pooled_contacts, pooled_act = [], []
    per: List[Dict] = []
    for c in cards:
        devices[c.get("device", "?")] += 1
        consents[c.get("consent", "?")] += 1
        licenses[c.get("license", "?")] += 1
        modes[c.get("data_mode", "?")] += 1
        total_frames += int(c.get("num_frames", 0) or 0)
        total_eps += int(c.get("num_episodes", 0) or 0)
        sig = None
        if c.get("data_mode") == "in_repo" and c.get("data_path"):
            sig = _load_signal_stats(registry_dir, c["data_path"])
            if sig:
                pooled_contacts.append(sig["contact_ratio"])
                pooled_act.append(sig["mean_action_magnitude"])
        per.append({
            "id": c.get("id"),
            "device": c.get("device"),
            "frames": int(c.get("num_frames", 0) or 0),
            "consent": c.get("consent"),
            "data_mode": c.get("data_mode"),
            "contact_ratio": round(sig["contact_ratio"], 3) if sig else None,
        })
    return {
        "contributions": len(cards),
        "total_frames": total_frames,
        "total_episodes": total_eps,
        "by_device": dict(devices),
        "by_consent": dict(consents),
        "by_license": dict(licenses),
        "by_data_mode": dict(modes),
        "pooled_contact_ratio": round(float(np.mean(pooled_contacts)), 3) if pooled_contacts else None,
        "pooled_mean_action_magnitude": round(float(np.mean(pooled_act)), 4) if pooled_act else None,
        "per_contribution": per,
    }


def write_report_md(agg: Dict, path: str) -> str:
    L = ["# EveryCam community data report", "",
         "_Auto-generated by `everycam aggregate` — do not edit by hand._", "",
         f"- **Contributions:** {agg['contributions']}",
         f"- **Total frames:** {agg['total_frames']:,}",
         f"- **Total episodes:** {agg['total_episodes']:,}"]
    if agg["pooled_contact_ratio"] is not None:
        L.append(f"- **Pooled hand-object contact ratio (in-repo):** {agg['pooled_contact_ratio']}")
    L += ["", "## By device", ""]
    L += [f"- {k}: {v}" for k, v in sorted(agg["by_device"].items(), key=lambda x: -x[1])] or ["- (none yet)"]
    L += ["", "## By consent", ""]
    L += [f"- {k}: {v}" for k, v in sorted(agg["by_consent"].items(), key=lambda x: -x[1])] or ["- (none yet)"]
    L += ["", "## Contributions", "",
          "| id | device | frames | consent | mode | contact |",
          "|---|---|---|---|---|---|"]
    for p in agg["per_contribution"]:
        c = p["contact_ratio"] if p["contact_ratio"] is not None else "—"
        L.append(f"| {p['id']} | {p['device']} | {p['frames']} | {p['consent']} | {p['data_mode']} | {c} |")
    if not agg["per_contribution"]:
        L.append("| (no contributions yet) | | | | | |")
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    return path
